name: noted
description: "A note app where you can save, sync your movies, tv series, and games."
publish_to: 'none'
version: 1.7.0+12

environment:
  sdk: ^3.8.1
  flutter: 3.32.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  analyzer: ^7.2.0
  rxdart: ^0.28.0
  freezed: ^3.0.6
  freezed_annotation: ^3.0.0
  flex_color_scheme: ^8.2.0
  get_it: ^8.0.3
  shared_preferences: ^2.5.3
  slang: ^4.7.1
  slang_flutter: ^4.7.0
  retrofit: ^4.4.2
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  internet_connection_checker_plus: ^2.7.1
  dartz: ^0.10.1
  json_annotation: ^4.9.0
  flutter_riverpod: ^2.6.1
  riverpod: ^2.6.1
  path: ^1.9.1
  path_provider: ^2.1.5
  fl_chart: ^1.0.0
  flutter_launcher_icons: ^0.14.3
  url_launcher: ^6.3.1
  file_picker: ^10.1.9
  flutter_dotenv: ^5.2.1
  objectbox: ^4.3.0
  objectbox_flutter_libs: ^4.3.0
  objectbox_generator: ^4.3.0
  flutter_animate: ^4.5.2
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.14
  flutter_lints: ^6.0.0
  json_serializable: ^6.9.5
  retrofit_generator: ^9.1.7

flutter_launcher_icons:
  android: true
  image_path: "assets/icon.png"

  windows:
    generate: true
    image_path: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
    - .env

  fonts:
    - family: El Messiri
      fonts:
        - asset: assets/fonts/main_font.ttf
